[package]
name = "SEIMI"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.30"
toml = "1.1.2"
serde = "1.0.228"
dotenvy = "0.15.7"
thiserror = "2.0.18"
env_logger = "0.11.10"
alloy = { version = "2", features = [ "full" ] }
tokio = { version = "1.52.3", features = [ "full" ] }
sqlx = { version = "0.9.0", features = [ "runtime-tokio", "postgres", "chrono", "bigdecimal" ] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }

